### ISSUE TITLE
Click missing in remote checksums

### ISSUE THREAD

**Issue by mandresm** [esm-tools/pool_tool#17]
If I use `ptool checksums-remote` with a machine that has no `click` module install I get the following error:

```
$ ptool checksums-remote albedo fesom2
found config for fesom2 on albedo0.dmawi.de
    pyexec=/albedo/soft/sw/spack-sw/python/3.10.4-daos5pe/bin/python
    path=/albedo/pool/FESOM2
    outfile=~/checksum_fesom2_albedo.csv
    ignore=.git
creating ssh connection to albedo
Password: 
calculating checksum for pool fesom2
Traceback (most recent call last):
  File "/albedo/home/mandresm/checksums.py", line 7, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Traceback (most recent call last):
  File "/Users/mandresm/opt/anaconda3/envs/ptool/bin/ptool", line 33, in <module>
    sys.exit(load_entry_point('ptool', 'console_scripts', 'ptool')())
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mandresm/Codes/pool_tool/ptool/cli.py", line 347, in checksums_remote
    remotechecksums.get_checksum(site, pool)
  File "/Users/mandresm/Codes/pool_tool/ptool/remotechecksums.py", line 102, in get_checksum
    scp.get(OUTFILE, rel_outfile)
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/paramiko/sftp_client.py", line 840, in get
    size = self.getfo(
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/paramiko/sftp_client.py", line 795, in getfo
    file_size = self.stat(remotepath).st_size
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/paramiko/sftp_client.py", line 857, in _request
    return self._read_response(num)
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/paramiko/sftp_client.py", line 909, in _read_response
    self._convert_status(msg)
  File "/Users/mandresm/opt/anaconda3/envs/ptool/lib/python3.9/site-packages/paramiko/sftp_client.py", line 938, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
```

**Comment by siligam** [comment]
With the new work-flow, `ptool checksum-remote` option is dropped. Now, the tool only provides `ptool checksums` for doing checksum. Still it is possible to do remote checksums using this command. It is documented in README.
