### ISSUE TITLE
analyse problems with csv arbitraty filenames

### ISSUE THREAD

**Issue by mandresm** [esm-tools/pool_tool#5]
analyse.py (for example `ptool summary <PATH1> <PATH2>`) expects that the PATHS have the following format: `name_project_machine.csv`. Otherwise, is through out a Traceback error. This is problematic because:

- `ptool checksums` does not enforce these file names, so it is very likely that users will confront this problem if they use checksums instead remote-checksums
- No error handling that tells the user exactly what's going on:
```bash
$ ptool summary asdasd.csv asdaqw.csv 
asdasd.csv
Traceback (most recent call last):
  File "/albedo/home/mandresm/.conda/envs/ptool/bin/ptool", line 33, in <module>
    sys.exit(load_entry_point('ptool', 'console_scripts', 'ptool')())
  File "/albedo/home/mandresm/.local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/albedo/home/mandresm/.local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/albedo/home/mandresm/.local/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/albedo/home/mandresm/.local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/albedo/home/mandresm/.local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/albedo/work/user/mandresm/pool_tool/pool/ptool/cli.py", line 209, in summary
    summary(
  File "/albedo/work/user/mandresm/pool_tool/pool/ptool/analyse.py", line 253, in summary
    left, left_dups = read_csv(
  File "/albedo/work/user/mandresm/pool_tool/pool/ptool/analyse.py", line 44, in read_csv
    _, pool, site = os.path.basename(filename).split("_")
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by siligam** [comment]
The current version totally relaxes the file names used for csv files. Also the config strategy is dropped for simplicity. These issues got auto resolved with the new work-flow of the tool.
